### PR TITLE
enable rule unknown_types

### PR DESCRIPTION
**Pull request by larshp**

### CODE REVIEW

**Comment by larshp** [comment]
as expected, the type `ZEIDE_NAD` is unknown

**Comment by larshp** [comment]
either the type must be added to the repository, or the `errorNamespace` adjusted, or add additional dependencies

**Comment by BlackmanCC** [comment]
@larshp  hhhmm. understand half of it.
why do I get this with 

> unknown_types: false

?
There are other types not included in the package e.g. zcx_isu_dex_all

**Comment by BlackmanCC** [comment]
@larshp just realized that the structure ZEIDE_NAME and ZEIDE_NAD are part of the original package where I found the issue

I will change the example

**Comment by larshp** [comment]
consider the `unknown_types` rule as part of the abaplint syntax check

you can decide how much or little syntax to have abaplint check

for structure ZEIDE_NAME and ZEIDE_NAD: either add it to the repository, exempt via the `errorNamespace`, add as a [local dependency in the repository, or external dependency](https://github.com/abapGit/abapGit/blob/main/abaplint.json#L8)

**Comment by BlackmanCC** [comment]
I will add it to the test repo and check again

**Pull request merged**
